export const exercises = [
  // Chest
  { name: "Barbell Bench Press", primaryMuscle: "Chest", equipment: "Barbell" },
  { name: "Incline Barbell Bench Press", primaryMuscle: "Chest", equipment: "Barbell" },
  { name: "Dumbbell Bench Press", primaryMuscle: "Chest", equipment: "Dumbbell" },
  { name: "Incline Dumbbell Press", primaryMuscle: "Chest", equipment: "Dumbbell" },
  { name: "Cable Fly", primaryMuscle: "Chest", equipment: "Cable" },
  { name: "Push-Up", primaryMuscle: "Chest", equipment: "Bodyweight" },
  { name: "Chest Dip", primaryMuscle: "Chest", equipment: "Bodyweight" },
  // Back
  { name: "Deadlift", primaryMuscle: "Back", equipment: "Barbell" },
  { name: "Barbell Row", primaryMuscle: "Back", equipment: "Barbell" },
  { name: "Pull-Up", primaryMuscle: "Back", equipment: "Bodyweight" },
  { name: "Chin-Up", primaryMuscle: "Back", equipment: "Bodyweight" },
  { name: "Lat Pulldown", primaryMuscle: "Back", equipment: "Cable" },
  { name: "Seated Cable Row", primaryMuscle: "Back", equipment: "Cable" },
  { name: "Dumbbell Row", primaryMuscle: "Back", equipment: "Dumbbell" },
  { name: "Face Pull", primaryMuscle: "Back", equipment: "Cable" },
  // Legs
  { name: "Back Squat", primaryMuscle: "Quads", equipment: "Barbell" },
  { name: "Front Squat", primaryMuscle: "Quads", equipment: "Barbell" },
  { name: "Leg Press", primaryMuscle: "Quads", equipment: "Machine" },
  { name: "Romanian Deadlift", primaryMuscle: "Hamstrings", equipment: "Barbell" },
  { name: "Leg Curl", primaryMuscle: "Hamstrings", equipment: "Machine" },
  { name: "Leg Extension", primaryMuscle: "Quads", equipment: "Machine" },
  { name: "Bulgarian Split Squat", primaryMuscle: "Quads", equipment: "Dumbbell" },
  { name: "Walking Lunge", primaryMuscle: "Quads", equipment: "Dumbbell" },
  { name: "Hip Thrust", primaryMuscle: "Glutes", equipment: "Barbell" },
  { name: "Calf Raise", primaryMuscle: "Calves", equipment: "Machine" },
  // Shoulders
  { name: "Overhead Press", primaryMuscle: "Shoulders", equipment: "Barbell" },
  { name: "Seated Dumbbell Press", primaryMuscle: "Shoulders", equipment: "Dumbbell" },
  { name: "Lateral Raise", primaryMuscle: "Shoulders", equipment: "Dumbbell" },
  { name: "Rear Delt Fly", primaryMuscle: "Shoulders", equipment: "Dumbbell" },
  { name: "Arnold Press", primaryMuscle: "Shoulders", equipment: "Dumbbell" },
  // Arms
  { name: "Barbell Curl", primaryMuscle: "Biceps", equipment: "Barbell" },
  { name: "Dumbbell Curl", primaryMuscle: "Biceps", equipment: "Dumbbell" },
  { name: "Hammer Curl", primaryMuscle: "Biceps", equipment: "Dumbbell" },
  { name: "Preacher Curl", primaryMuscle: "Biceps", equipment: "Barbell" },
  { name: "Triceps Pushdown", primaryMuscle: "Triceps", equipment: "Cable" },
  { name: "Overhead Triceps Extension", primaryMuscle: "Triceps", equipment: "Dumbbell" },
  { name: "Skull Crusher", primaryMuscle: "Triceps", equipment: "Barbell" },
  { name: "Close-Grip Bench Press", primaryMuscle: "Triceps", equipment: "Barbell" },
  // Core
  { name: "Plank", primaryMuscle: "Core", equipment: "Bodyweight" },
  { name: "Hanging Leg Raise", primaryMuscle: "Core", equipment: "Bodyweight" },
  { name: "Cable Crunch", primaryMuscle: "Core", equipment: "Cable" },
  { name: "Ab Wheel Rollout", primaryMuscle: "Core", equipment: "Bodyweight" },
];
